elasticsearch:
  container_name: elasticsearch
  image: elasticsearch:latest
  command: elasticsearch -Dscript.engine.groovy.inline.search=on -Des.network.host=0.0.0.0 -Des.cluster.name=elasticsearch -Ddiscovery.zen.minimum_master_nodes=1
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  container_name: logstash
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
    - "5000:5000/udp"
    - "5100:5100/udp"
kibana:
  container_name: kibana
  build: kibana/
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch

logspout:
  container_name: logspout
  image: oneforone/logspout
  command: raw://10.10.1.12:5000?filter.name=nginx
  ports:
    - "8000:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  environment:
    - ROUTE_URIS=logstash://10.10.1.12:5000
